# Generated by Django 5.0.2 on 2025-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionPoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
