# Generated by Django 5.1.6 on 2025-04-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
