# Generated by Django 5.1.6 on 2025-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionPoint', '0002_cv_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='upload_type',
            field=models.CharField(choices=[('document', 'Document (PDF)'), ('image', 'Photo (JPG, PNG)'), ('audio', 'Voice Recording')], max_length=20),
        ),
    ]
