# Generated by Django 5.1.6 on 2025-04-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobSeekerPortal', '0001_initial'),
        ('UserManagement', '0003_employerprofile_jobseekerprofile_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.jobseekerprofile')),
                ('related_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekerPortal.joboffer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Medio tiempo'), ('contract', 'Contrato'), ('freelance', 'Freelance'), ('internship', 'Pasantía')], max_length=50)),
                ('remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekerPortal.joboffer')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.jobseekerprofile')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('job_offer', 'job_seeker')},
            },
        ),
    ]
