# Generated by Django 5.1.6 on 2025-04-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatematch',
            name='candidate_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='job_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
