# Generated by Django 5.1.6 on 2025-04-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionPoint', '0003_alter_cv_upload_type'),
        ('UserManagement', '0002_alter_userprofile_options_userprofile_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501-1000', '501-1000 empleados'), ('1000+', 'Más de 1000 empleados')], max_length=10, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_location', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Empleador',
                'verbose_name_plural': 'Perfiles de Empleadores',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('professional_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Habilidades separadas por comas', null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, help_text='Idiomas separados por comas', max_length=200, null=True)),
                ('availability', models.CharField(blank=True, choices=[('immediate', 'Inmediata'), ('2_weeks', '2 semanas'), ('1_month', '1 mes'), ('negotiable', 'Negociable')], max_length=20, null=True)),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remote_work', models.BooleanField(default=False, verbose_name='Disponible para trabajo remoto')),
                ('has_cv', models.BooleanField(default=False)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseeker_profiles', to='CollectionPoint.cv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Candidato',
                'verbose_name_plural': 'Perfiles de Candidatos',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['profile_completed'], name='UserManagem_profile_82641b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['profile_completed'], name='UserManagem_profile_92771f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['has_cv'], name='UserManagem_has_cv_7bc78f_idx'),
        ),
    ]
